/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;

/**
 *
 * @author Luusc
 */
public class FrmPedidos extends javax.swing.JFrame {

    /**
     * Creates new form FrmPedidos
     */
    public FrmPedidos() {
        initComponents();
        this.setLocationRelativeTo(null);
    
        //Colocar linha azul na borda descrição
         linhaD.setBorder(BorderFactory.createMatteBorder (0,0,2,0, Color.blue));
         linhaD1.setBorder(BorderFactory.createMatteBorder (0,0,2,0, Color.blue));
         linhaD2.setBorder(BorderFactory.createMatteBorder (0,0,2,0, Color.blue));
         linhaD3.setBorder(BorderFactory.createMatteBorder (0,0,2,0, Color.blue));
         linhaD4.setBorder(BorderFactory.createMatteBorder (0,0,2,0, Color.blue));
         linhaD5.setBorder(BorderFactory.createMatteBorder (0,0,2,0, Color.blue));
         linhaD6.setBorder(BorderFactory.createMatteBorder (0,0,2,0, Color.blue));
         linhaD7.setBorder(BorderFactory.createMatteBorder (0,0,2,0, Color.blue));
         linhaD8.setBorder(BorderFactory.createMatteBorder (0,0,2,0, Color.blue));
         linhaD9.setBorder(BorderFactory.createMatteBorder (0,0,2,0, Color.blue));
         linhaD10.setBorder(BorderFactory.createMatteBorder (0,0,2,0, Color.blue));
         linhaD11.setBorder(BorderFactory.createMatteBorder (0,0,2,0, Color.blue));
         linhaD12.setBorder(BorderFactory.createMatteBorder (0,0,2,0, Color.blue));
         linhaD13.setBorder(BorderFactory.createMatteBorder (0,0,2,0, Color.blue));
         
         
         
    
         
         //Colocar linha azul na borda und
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        panelDesc = new javax.swing.JPanel();
        linhaD = new javax.swing.JTextField();
        linhaD1 = new javax.swing.JTextField();
        linhaD2 = new javax.swing.JTextField();
        linhaD3 = new javax.swing.JTextField();
        linhaD4 = new javax.swing.JTextField();
        linhaD5 = new javax.swing.JTextField();
        linhaD6 = new javax.swing.JTextField();
        linhaD7 = new javax.swing.JTextField();
        linhaD8 = new javax.swing.JTextField();
        linhaD9 = new javax.swing.JTextField();
        linhaD10 = new javax.swing.JTextField();
        linhaD11 = new javax.swing.JTextField();
        linhaD12 = new javax.swing.JTextField();
        linhaD13 = new javax.swing.JTextField();
        panelVU = new javax.swing.JPanel();
        linhaVU = new javax.swing.JTextField();
        linhaVU1 = new javax.swing.JTextField();
        linhaVU2 = new javax.swing.JTextField();
        linhaVU3 = new javax.swing.JTextField();
        linhaVU4 = new javax.swing.JTextField();
        linhaVU5 = new javax.swing.JTextField();
        linhaVU6 = new javax.swing.JTextField();
        linhaVU7 = new javax.swing.JTextField();
        linhaVU8 = new javax.swing.JTextField();
        linhaVU9 = new javax.swing.JTextField();
        linhaVU10 = new javax.swing.JTextField();
        linhaVU11 = new javax.swing.JTextField();
        linhaVU12 = new javax.swing.JTextField();
        linhaVU13 = new javax.swing.JTextField();
        panelVT = new javax.swing.JPanel();
        linhaVT = new javax.swing.JTextField();
        linhaVT1 = new javax.swing.JTextField();
        linhaVT2 = new javax.swing.JTextField();
        linhaVT3 = new javax.swing.JTextField();
        linhaVT4 = new javax.swing.JTextField();
        linhaVT5 = new javax.swing.JTextField();
        linhaVT6 = new javax.swing.JTextField();
        linhaVT7 = new javax.swing.JTextField();
        linhaVT8 = new javax.swing.JTextField();
        linhaVT9 = new javax.swing.JTextField();
        linhaVT10 = new javax.swing.JTextField();
        linhaVT11 = new javax.swing.JTextField();
        linhaVT12 = new javax.swing.JTextField();
        linhaVT13 = new javax.swing.JTextField();
        linhaVT14 = new javax.swing.JTextField();
        linhaVT15 = new javax.swing.JTextField();
        linhaVT16 = new javax.swing.JTextField();
        linhaVT17 = new javax.swing.JTextField();
        linhaVT18 = new javax.swing.JTextField();
        linhaVT19 = new javax.swing.JTextField();

        jInternalFrame1.setVisible(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("FrmPedidos"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(new java.awt.GridLayout());

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(700, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDesc.setBackground(new java.awt.Color(255, 255, 255));
        panelDesc.setLayout(new java.awt.GridLayout(20, 1));

        linhaD.setPreferredSize(new java.awt.Dimension(400, 15));
        panelDesc.add(linhaD);

        linhaD1.setPreferredSize(new java.awt.Dimension(400, 15));
        panelDesc.add(linhaD1);

        linhaD2.setPreferredSize(new java.awt.Dimension(400, 15));
        panelDesc.add(linhaD2);

        linhaD3.setPreferredSize(new java.awt.Dimension(400, 15));
        panelDesc.add(linhaD3);

        linhaD4.setPreferredSize(new java.awt.Dimension(400, 15));
        panelDesc.add(linhaD4);

        linhaD5.setPreferredSize(new java.awt.Dimension(400, 15));
        panelDesc.add(linhaD5);

        linhaD6.setPreferredSize(new java.awt.Dimension(400, 15));
        panelDesc.add(linhaD6);

        linhaD7.setPreferredSize(new java.awt.Dimension(400, 15));
        panelDesc.add(linhaD7);

        linhaD8.setPreferredSize(new java.awt.Dimension(400, 15));
        panelDesc.add(linhaD8);

        linhaD9.setPreferredSize(new java.awt.Dimension(400, 15));
        panelDesc.add(linhaD9);

        linhaD10.setPreferredSize(new java.awt.Dimension(400, 15));
        panelDesc.add(linhaD10);

        linhaD11.setPreferredSize(new java.awt.Dimension(400, 15));
        panelDesc.add(linhaD11);

        linhaD12.setPreferredSize(new java.awt.Dimension(400, 15));
        panelDesc.add(linhaD12);

        linhaD13.setPreferredSize(new java.awt.Dimension(400, 15));
        panelDesc.add(linhaD13);

        jPanel1.add(panelDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 400, 700));

        panelVU.setBackground(new java.awt.Color(255, 255, 255));
        panelVU.setLayout(new java.awt.GridLayout(20, 1));

        linhaVU.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVU.add(linhaVU);

        linhaVU1.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVU.add(linhaVU1);

        linhaVU2.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVU.add(linhaVU2);

        linhaVU3.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVU.add(linhaVU3);

        linhaVU4.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVU.add(linhaVU4);

        linhaVU5.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVU.add(linhaVU5);

        linhaVU6.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVU.add(linhaVU6);

        linhaVU7.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVU.add(linhaVU7);

        linhaVU8.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVU.add(linhaVU8);

        linhaVU9.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVU.add(linhaVU9);

        linhaVU10.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVU.add(linhaVU10);

        linhaVU11.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVU.add(linhaVU11);

        linhaVU12.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVU.add(linhaVU12);

        linhaVU13.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVU.add(linhaVU13);

        jPanel1.add(panelVU, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 50, 700));

        panelVT.setBackground(new java.awt.Color(255, 255, 255));
        panelVT.setLayout(new java.awt.GridLayout(20, 0));

        linhaVT.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVT.add(linhaVT);

        linhaVT1.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVT.add(linhaVT1);

        linhaVT2.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVT.add(linhaVT2);

        linhaVT3.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVT.add(linhaVT3);

        linhaVT4.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVT.add(linhaVT4);

        linhaVT5.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVT.add(linhaVT5);

        linhaVT6.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVT.add(linhaVT6);

        linhaVT7.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVT.add(linhaVT7);

        linhaVT8.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVT.add(linhaVT8);

        linhaVT9.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVT.add(linhaVT9);

        linhaVT10.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVT.add(linhaVT10);

        linhaVT11.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVT.add(linhaVT11);

        linhaVT12.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVT.add(linhaVT12);

        linhaVT13.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVT.add(linhaVT13);

        linhaVT14.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVT.add(linhaVT14);

        linhaVT15.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVT.add(linhaVT15);

        linhaVT16.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVT.add(linhaVT16);

        linhaVT17.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVT.add(linhaVT17);

        linhaVT18.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVT.add(linhaVT18);

        linhaVT19.setPreferredSize(new java.awt.Dimension(400, 15));
        panelVT.add(linhaVT19);

        jPanel1.add(panelVT, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 50, 700));

        jScrollPane2.setViewportView(jPanel1);

        getContentPane().add(jScrollPane2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmPedidos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField linhaD;
    private javax.swing.JTextField linhaD1;
    private javax.swing.JTextField linhaD10;
    private javax.swing.JTextField linhaD11;
    private javax.swing.JTextField linhaD12;
    private javax.swing.JTextField linhaD13;
    private javax.swing.JTextField linhaD2;
    private javax.swing.JTextField linhaD3;
    private javax.swing.JTextField linhaD4;
    private javax.swing.JTextField linhaD5;
    private javax.swing.JTextField linhaD6;
    private javax.swing.JTextField linhaD7;
    private javax.swing.JTextField linhaD8;
    private javax.swing.JTextField linhaD9;
    private javax.swing.JTextField linhaVT;
    private javax.swing.JTextField linhaVT1;
    private javax.swing.JTextField linhaVT10;
    private javax.swing.JTextField linhaVT11;
    private javax.swing.JTextField linhaVT12;
    private javax.swing.JTextField linhaVT13;
    private javax.swing.JTextField linhaVT14;
    private javax.swing.JTextField linhaVT15;
    private javax.swing.JTextField linhaVT16;
    private javax.swing.JTextField linhaVT17;
    private javax.swing.JTextField linhaVT18;
    private javax.swing.JTextField linhaVT19;
    private javax.swing.JTextField linhaVT2;
    private javax.swing.JTextField linhaVT3;
    private javax.swing.JTextField linhaVT4;
    private javax.swing.JTextField linhaVT5;
    private javax.swing.JTextField linhaVT6;
    private javax.swing.JTextField linhaVT7;
    private javax.swing.JTextField linhaVT8;
    private javax.swing.JTextField linhaVT9;
    private javax.swing.JTextField linhaVU;
    private javax.swing.JTextField linhaVU1;
    private javax.swing.JTextField linhaVU10;
    private javax.swing.JTextField linhaVU11;
    private javax.swing.JTextField linhaVU12;
    private javax.swing.JTextField linhaVU13;
    private javax.swing.JTextField linhaVU2;
    private javax.swing.JTextField linhaVU3;
    private javax.swing.JTextField linhaVU4;
    private javax.swing.JTextField linhaVU5;
    private javax.swing.JTextField linhaVU6;
    private javax.swing.JTextField linhaVU7;
    private javax.swing.JTextField linhaVU8;
    private javax.swing.JTextField linhaVU9;
    private javax.swing.JPanel panelDesc;
    private javax.swing.JPanel panelVT;
    private javax.swing.JPanel panelVU;
    // End of variables declaration//GEN-END:variables
}
