/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import java.awt.Color;
import java.awt.Font;
import static java.awt.PageAttributes.MediaType.C;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author Luusc
 */
public class FrmPedidos extends javax.swing.JFrame {

    /**
     * Creates new form FrmPedidos
     */
    public FrmPedidos() {
        initComponents();
        txtCod.setBackground(Color.blue);
        this.setLocationRelativeTo(null);
        table.getTableHeader().setOpaque(false);
        table.getTableHeader().setBackground(Color.white);
        txtData.setBackground(Color.blue);
        razaoBF.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        txtRazao.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        txtCNPJ.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        txtTel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        txtEmail.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        txtVendedor.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        txtNum.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        txtEnde.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        txtEndeBF.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        txtTelBF.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        txtCNPJBF.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
      
        
                        
    
         
         //Colocar linha azul na borda und
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txtData = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        txtNum = new app.bolivia.swing.JCTextField();
        cBox = new javax.swing.JComboBox<>();
        txtEnde = new app.bolivia.swing.JCTextField();
        txtRazao = new app.bolivia.swing.JCTextField();
        txtCNPJ = new javax.swing.JFormattedTextField();
        txtTel = new javax.swing.JFormattedTextField();
        txtEmail = new app.bolivia.swing.JCTextField();
        txtVendedor = new app.bolivia.swing.JCTextField();
        jButton1 = new javax.swing.JButton();
        panelDados = new javax.swing.JPanel();
        txtEndeBF = new app.bolivia.swing.JCTextField();
        razaoBF = new app.bolivia.swing.JCTextField();
        lblRazao = new javax.swing.JLabel();
        lblCNPJ = new javax.swing.JLabel();
        lblEndeBF = new javax.swing.JLabel();
        lblEndeBF2 = new javax.swing.JLabel();
        txtTelBF = new javax.swing.JFormattedTextField();
        txtCNPJBF = new javax.swing.JFormattedTextField();
        txtCod = new app.bolivia.swing.JCTextField();

        jInternalFrame1.setVisible(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulário de Compras");
        setBackground(new java.awt.Color(255, 255, 255));
        setName("FrmPedidos"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(700, 600));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setOpaque(false);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(650, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setToolTipText("");
        jPanel2.setDoubleBuffered(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 800));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setAutoCreateRowSorter(true);
        table.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Qtde.", "Und.", "Descrição", "Valor Un.", "Valor Total"
            }
        ));
        table.setGridColor(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        table.setIntercellSpacing(new java.awt.Dimension(4, 4));
        table.setOpaque(false);
        table.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setPreferredWidth(50);
            table.getColumnModel().getColumn(1).setPreferredWidth(50);
            table.getColumnModel().getColumn(2).setPreferredWidth(500);
            table.getColumnModel().getColumn(3).setPreferredWidth(100);
            table.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 337, 660, -1));

        txtData.setBorder(null);
        txtData.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtData.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtData.setPreferredSize(new java.awt.Dimension(6, 25));
        jPanel2.add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 70, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fonecedor:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 3, 14), new java.awt.Color(0, 51, 255))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNum.setBorder(null);
        txtNum.setForeground(new java.awt.Color(0, 0, 204));
        txtNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNum.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNum.setPlaceholder("Núm.");
        jPanel1.add(txtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 50, 25));

        cBox.setEditable(true);
        cBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rua", "Av.", "Trv." }));
        cBox.setBorder(null);
        cBox.setOpaque(false);
        jPanel1.add(cBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 50, 25));

        txtEnde.setBorder(null);
        txtEnde.setForeground(new java.awt.Color(0, 0, 204));
        txtEnde.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtEnde.setPlaceholder("Endereço");
        txtEnde.setPreferredSize(new java.awt.Dimension(200, 25));
        txtEnde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndeActionPerformed(evt);
            }
        });
        jPanel1.add(txtEnde, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 160, -1));

        txtRazao.setBorder(null);
        txtRazao.setForeground(new java.awt.Color(0, 0, 204));
        txtRazao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtRazao.setPlaceholder("Razão Social");
        txtRazao.setPreferredSize(new java.awt.Dimension(200, 25));
        txtRazao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazaoActionPerformed(evt);
            }
        });
        jPanel1.add(txtRazao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 400, -1));

        txtCNPJ.setBorder(null);
        txtCNPJ.setForeground(new java.awt.Color(0, 0, 204));
        try {
            txtCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCNPJ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCNPJ.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCNPJ.setPreferredSize(new java.awt.Dimension(109, 25));
        jPanel1.add(txtCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 25));

        txtTel.setBorder(null);
        txtTel.setForeground(new java.awt.Color(0, 0, 204));
        try {
            txtTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtTel.setPreferredSize(new java.awt.Dimension(109, 25));
        jPanel1.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 100, 25));

        txtEmail.setBorder(null);
        txtEmail.setForeground(new java.awt.Color(0, 0, 204));
        txtEmail.setAutoscrolls(false);
        txtEmail.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtEmail.setPlaceholder("E-mail");
        txtEmail.setPreferredSize(new java.awt.Dimension(200, 25));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 160, -1));

        txtVendedor.setBorder(null);
        txtVendedor.setForeground(new java.awt.Color(0, 0, 204));
        txtVendedor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtVendedor.setPlaceholder("Vendedor");
        txtVendedor.setPreferredSize(new java.awt.Dimension(200, 25));
        txtVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVendedorActionPerformed(evt);
            }
        });
        jPanel1.add(txtVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 160, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 660, 100));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconLogin/iconSair35px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 30, -1));

        panelDados.setBackground(new java.awt.Color(255, 255, 255));
        panelDados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados da Empresa:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 3, 14), new java.awt.Color(0, 51, 255))); // NOI18N
        panelDados.setOpaque(false);
        panelDados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEndeBF.setBorder(null);
        txtEndeBF.setForeground(new java.awt.Color(0, 0, 204));
        txtEndeBF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEndeBF.setText(" AV. JORGE AMADO, Nº 920, BAIRRO JARDINS, ARACAJU-SE");
        txtEndeBF.setFocusable(false);
        txtEndeBF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtEndeBF.setPlaceholder("Endereço");
        txtEndeBF.setPreferredSize(new java.awt.Dimension(200, 25));
        txtEndeBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndeBFActionPerformed(evt);
            }
        });
        panelDados.add(txtEndeBF, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 340, -1));

        razaoBF.setEditable(false);
        razaoBF.setBackground(new java.awt.Color(255, 255, 255));
        razaoBF.setBorder(null);
        razaoBF.setForeground(new java.awt.Color(0, 0, 204));
        razaoBF.setText("  BAROS FILHOS CONTABILIDADE & SERVIÇOS LTDA");
        razaoBF.setFocusable(false);
        razaoBF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        razaoBF.setPlaceholder("Razão Social");
        razaoBF.setPreferredSize(new java.awt.Dimension(200, 25));
        razaoBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                razaoBFActionPerformed(evt);
            }
        });
        panelDados.add(razaoBF, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 300, -1));

        lblRazao.setBackground(new java.awt.Color(0, 51, 204));
        lblRazao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRazao.setForeground(new java.awt.Color(255, 255, 255));
        lblRazao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRazao.setText("Razão Social");
        lblRazao.setOpaque(true);
        panelDados.add(lblRazao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 25));

        lblCNPJ.setBackground(new java.awt.Color(0, 51, 204));
        lblCNPJ.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCNPJ.setForeground(new java.awt.Color(255, 255, 255));
        lblCNPJ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCNPJ.setText("CNPJ");
        lblCNPJ.setOpaque(true);
        panelDados.add(lblCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 30, 25));

        lblEndeBF.setBackground(new java.awt.Color(0, 51, 204));
        lblEndeBF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEndeBF.setForeground(new java.awt.Color(255, 255, 255));
        lblEndeBF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEndeBF.setText("Endereço");
        lblEndeBF.setOpaque(true);
        panelDados.add(lblEndeBF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, 25));

        lblEndeBF2.setBackground(new java.awt.Color(0, 51, 204));
        lblEndeBF2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEndeBF2.setForeground(new java.awt.Color(255, 255, 255));
        lblEndeBF2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEndeBF2.setText("Tel");
        lblEndeBF2.setOpaque(true);
        panelDados.add(lblEndeBF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 30, 25));

        txtTelBF.setBorder(null);
        txtTelBF.setForeground(new java.awt.Color(0, 0, 204));
        try {
            txtTelBF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelBF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelBF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtTelBF.setPreferredSize(new java.awt.Dimension(109, 25));
        panelDados.add(txtTelBF, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 120, -1));

        txtCNPJBF.setBorder(null);
        txtCNPJBF.setForeground(new java.awt.Color(0, 0, 204));
        try {
            txtCNPJBF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCNPJBF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCNPJBF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCNPJBF.setPreferredSize(new java.awt.Dimension(109, 25));
        panelDados.add(txtCNPJBF, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 120, -1));

        jPanel2.add(panelDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 660, 100));

        txtCod.setBorder(null);
        jPanel2.add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 50, 25));

        jScrollPane2.setViewportView(jPanel2);

        getContentPane().add(jScrollPane2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRazaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazaoActionPerformed
      
    }//GEN-LAST:event_txtRazaoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEndeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndeActionPerformed

    private void txtVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVendedorActionPerformed

    private void txtEndeBFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndeBFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndeBFActionPerformed

    private void razaoBFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_razaoBFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_razaoBFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmPedidos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCNPJ;
    private javax.swing.JLabel lblEndeBF;
    private javax.swing.JLabel lblEndeBF2;
    private javax.swing.JLabel lblRazao;
    private javax.swing.JPanel panelDados;
    private app.bolivia.swing.JCTextField razaoBF;
    private javax.swing.JTable table;
    private javax.swing.JFormattedTextField txtCNPJ;
    private javax.swing.JFormattedTextField txtCNPJBF;
    private app.bolivia.swing.JCTextField txtCod;
    private javax.swing.JFormattedTextField txtData;
    private app.bolivia.swing.JCTextField txtEmail;
    private app.bolivia.swing.JCTextField txtEnde;
    private app.bolivia.swing.JCTextField txtEndeBF;
    private app.bolivia.swing.JCTextField txtNum;
    private app.bolivia.swing.JCTextField txtRazao;
    private javax.swing.JFormattedTextField txtTel;
    private javax.swing.JFormattedTextField txtTelBF;
    private app.bolivia.swing.JCTextField txtVendedor;
    // End of variables declaration//GEN-END:variables
}
