/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/**
 *
 * @author Luusc
 */
public class FrmPedidos extends javax.swing.JFrame {

    /**
     * Creates new form FrmPedidos
     */
    public FrmPedidos() {
        initComponents();
        this.setLocationRelativeTo(null);
        table.getTableHeader().setOpaque(false);
        table.getTableHeader().setBackground(Color.white);
        txtRazao.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        txtCNPJ.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        txtTel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        txtEmail.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        txtVendedor.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        txtNum.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        txtEnde.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        //Colocar linha azul na borda descrição
         
         
    
         
         //Colocar linha azul na borda und
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txtVendedor = new app.bolivia.swing.JCTextField();
        txtEnde = new app.bolivia.swing.JCTextField();
        txtEmail = new app.bolivia.swing.JCTextField();
        txtRazao = new app.bolivia.swing.JCTextField();
        txtTel = new javax.swing.JFormattedTextField();
        txtCNPJ = new javax.swing.JFormattedTextField();
        cBox = new javax.swing.JComboBox<>();
        txtNum = new app.bolivia.swing.JCTextField();
        btnSair = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("FrmPedidos"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(680, 600));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(650, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setToolTipText("");
        jPanel2.setDoubleBuffered(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 800));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setAutoCreateRowSorter(true);
        table.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Qtde.", "Und.", "Descrição", "Valor Un.", "Valor Total"
            }
        ));
        table.setGridColor(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        table.setOpaque(false);
        table.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setPreferredWidth(50);
            table.getColumnModel().getColumn(1).setPreferredWidth(50);
            table.getColumnModel().getColumn(2).setPreferredWidth(500);
            table.getColumnModel().getColumn(3).setPreferredWidth(100);
            table.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 240, 640, -1));

        txtVendedor.setBorder(null);
        txtVendedor.setPlaceholder("Vendedor");
        txtVendedor.setPreferredSize(new java.awt.Dimension(200, 25));
        txtVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVendedorActionPerformed(evt);
            }
        });
        jPanel2.add(txtVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 130, -1));

        txtEnde.setBorder(null);
        txtEnde.setPlaceholder("Endereço");
        txtEnde.setPreferredSize(new java.awt.Dimension(200, 25));
        txtEnde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndeActionPerformed(evt);
            }
        });
        jPanel2.add(txtEnde, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 130, -1));

        txtEmail.setBorder(null);
        txtEmail.setPlaceholder("E-mail");
        txtEmail.setPreferredSize(new java.awt.Dimension(200, 25));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 170, -1));

        txtRazao.setBorder(null);
        txtRazao.setPlaceholder("Razão Social");
        txtRazao.setPreferredSize(new java.awt.Dimension(200, 25));
        txtRazao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazaoActionPerformed(evt);
            }
        });
        jPanel2.add(txtRazao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 450, -1));

        txtTel.setBorder(null);
        try {
            txtTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTel.setPreferredSize(new java.awt.Dimension(109, 25));
        jPanel2.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 130, 25));

        txtCNPJ.setBorder(null);
        try {
            txtCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCNPJ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCNPJ.setPreferredSize(new java.awt.Dimension(109, 25));
        jPanel2.add(txtCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, 25));

        cBox.setEditable(true);
        cBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rua", "Av.", "Trv." }));
        cBox.setBorder(null);
        cBox.setOpaque(false);
        jPanel2.add(cBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 50, 25));

        txtNum.setBorder(null);
        txtNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNum.setPlaceholder("Núm.");
        jPanel2.add(txtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 40, 25));

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconLogin/iconSair35px.png"))); // NOI18N
        btnSair.setContentAreaFilled(false);
        btnSair.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconLogin/iconSairRed35px.png"))); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel2.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 0, 40, -1));

        jScrollPane2.setViewportView(jPanel2);

        getContentPane().add(jScrollPane2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRazaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazaoActionPerformed
      
    }//GEN-LAST:event_txtRazaoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEndeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndeActionPerformed

    private void txtVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVendedorActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmPedidos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cBox;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    private javax.swing.JFormattedTextField txtCNPJ;
    private app.bolivia.swing.JCTextField txtEmail;
    private app.bolivia.swing.JCTextField txtEnde;
    private app.bolivia.swing.JCTextField txtNum;
    private app.bolivia.swing.JCTextField txtRazao;
    private javax.swing.JFormattedTextField txtTel;
    private app.bolivia.swing.JCTextField txtVendedor;
    // End of variables declaration//GEN-END:variables
}
