/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import java.awt.Color;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Luusc
 */
public class FrmProdutos extends javax.swing.JFrame {

  
    /**
     * 
     * Creates new form FrmProd
     */
    public FrmProdutos() {
        initComponents();
    
        
        
        // txtCod.setBackground(new Color(0,51,204));
        this.setLocationRelativeTo(null);
        table.getTableHeader().setOpaque(false);
        table.getTableHeader().setBackground(Color.white);
       // txtData.setBackground(new Color(0,51,204));
        razaoBF.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        txtRazao.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        txtCNPJ.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        txtTel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        txtEmail.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        txtVendedor.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        txtNum.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        txtEnde.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        txtEndeBF.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        txtTelBF.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
        txtCNPJBF.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.blue));
       
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        central = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        txtCod = new app.bolivia.swing.JCTextField();
        jLabel1 = new javax.swing.JLabel();
        txtHora = new javax.swing.JLabel();
        txtData = new javax.swing.JLabel();
        panelDosDados = new javax.swing.JScrollPane();
        panelCentraldoScroll = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtNum = new app.bolivia.swing.JCTextField();
        cBox = new javax.swing.JComboBox<>();
        txtEnde = new app.bolivia.swing.JCTextField();
        txtRazao = new app.bolivia.swing.JCTextField();
        txtCNPJ = new javax.swing.JFormattedTextField();
        txtTel = new javax.swing.JFormattedTextField();
        txtEmail = new app.bolivia.swing.JCTextField();
        txtVendedor = new app.bolivia.swing.JCTextField();
        panelDados = new javax.swing.JPanel();
        txtEndeBF = new app.bolivia.swing.JCTextField();
        razaoBF = new app.bolivia.swing.JCTextField();
        lblRazao = new javax.swing.JLabel();
        lblCNPJ = new javax.swing.JLabel();
        lblEndeBF = new javax.swing.JLabel();
        lblEndeBF2 = new javax.swing.JLabel();
        txtTelBF = new javax.swing.JFormattedTextField();
        txtCNPJBF = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnadd = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        txtUnd = new javax.swing.JTextField();
        txtQtde = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        valorUN = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(715, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        central.setPreferredSize(new java.awt.Dimension(720, 700));
        central.setLayout(new java.awt.BorderLayout());

        top.setBackground(new java.awt.Color(255, 255, 255));
        top.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCod.setEditable(false);
        txtCod.setBackground(new java.awt.Color(0, 51, 204));
        txtCod.setBorder(null);
        txtCod.setForeground(new java.awt.Color(255, 255, 255));
        txtCod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCod.setToolTipText("");
        txtCod.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCod.setPhColor(new java.awt.Color(255, 255, 255));
        txtCod.setPlaceholder("Cód.");
        top.add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 60, 25));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconLogin/logo-fundo-transparente-2.png"))); // NOI18N
        top.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        txtHora.setBackground(new java.awt.Color(0, 51, 204));
        txtHora.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtHora.setForeground(new java.awt.Color(255, 255, 255));
        txtHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtHora.setOpaque(true);
        top.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 90, 25));

        txtData.setBackground(new java.awt.Color(0, 51, 204));
        txtData.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtData.setForeground(new java.awt.Color(255, 255, 255));
        txtData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtData.setOpaque(true);
        top.add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 90, 25));

        central.add(top, java.awt.BorderLayout.PAGE_START);

        panelDosDados.setBorder(null);

        panelCentraldoScroll.setBackground(new java.awt.Color(255, 255, 255));
        panelCentraldoScroll.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fonecedor:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 3, 14), new java.awt.Color(0, 51, 255))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNum.setBorder(null);
        txtNum.setForeground(new java.awt.Color(0, 0, 204));
        txtNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNum.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNum.setPlaceholder("Núm.");
        jPanel1.add(txtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 50, 25));

        cBox.setEditable(true);
        cBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rua", "Av.", "Trv." }));
        cBox.setBorder(null);
        cBox.setOpaque(false);
        jPanel1.add(cBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 50, 25));

        txtEnde.setBorder(null);
        txtEnde.setForeground(new java.awt.Color(0, 0, 204));
        txtEnde.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtEnde.setPlaceholder("Endereço");
        txtEnde.setPreferredSize(new java.awt.Dimension(200, 25));
        txtEnde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndeActionPerformed(evt);
            }
        });
        jPanel1.add(txtEnde, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 160, -1));

        txtRazao.setBorder(null);
        txtRazao.setForeground(new java.awt.Color(0, 0, 204));
        txtRazao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtRazao.setPlaceholder("Razão Social");
        txtRazao.setPreferredSize(new java.awt.Dimension(200, 25));
        txtRazao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazaoActionPerformed(evt);
            }
        });
        jPanel1.add(txtRazao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 400, -1));

        txtCNPJ.setBorder(null);
        txtCNPJ.setForeground(new java.awt.Color(0, 0, 204));
        try {
            txtCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCNPJ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCNPJ.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCNPJ.setPreferredSize(new java.awt.Dimension(109, 25));
        jPanel1.add(txtCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 25));

        txtTel.setBorder(null);
        txtTel.setForeground(new java.awt.Color(0, 0, 204));
        try {
            txtTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtTel.setPreferredSize(new java.awt.Dimension(109, 25));
        jPanel1.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 100, 25));

        txtEmail.setBorder(null);
        txtEmail.setForeground(new java.awt.Color(0, 0, 204));
        txtEmail.setAutoscrolls(false);
        txtEmail.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtEmail.setPlaceholder("E-mail");
        txtEmail.setPreferredSize(new java.awt.Dimension(200, 25));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 160, -1));

        txtVendedor.setBorder(null);
        txtVendedor.setForeground(new java.awt.Color(0, 0, 204));
        txtVendedor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtVendedor.setPlaceholder("Vendedor");
        txtVendedor.setPreferredSize(new java.awt.Dimension(200, 25));
        txtVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVendedorActionPerformed(evt);
            }
        });
        jPanel1.add(txtVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 160, -1));

        panelCentraldoScroll.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 660, 100));

        panelDados.setBackground(new java.awt.Color(255, 255, 255));
        panelDados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados da Empresa:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 3, 14), new java.awt.Color(0, 51, 255))); // NOI18N
        panelDados.setOpaque(false);
        panelDados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEndeBF.setEditable(false);
        txtEndeBF.setBackground(new java.awt.Color(255, 255, 255));
        txtEndeBF.setBorder(null);
        txtEndeBF.setForeground(new java.awt.Color(0, 0, 204));
        txtEndeBF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEndeBF.setText(" AV. JORGE AMADO, Nº 920, BAIRRO JARDINS, ARACAJU-SE");
        txtEndeBF.setFocusable(false);
        txtEndeBF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtEndeBF.setPlaceholder("Endereço");
        txtEndeBF.setPreferredSize(new java.awt.Dimension(200, 25));
        txtEndeBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndeBFActionPerformed(evt);
            }
        });
        panelDados.add(txtEndeBF, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 340, -1));

        razaoBF.setEditable(false);
        razaoBF.setBackground(new java.awt.Color(255, 255, 255));
        razaoBF.setBorder(null);
        razaoBF.setForeground(new java.awt.Color(0, 0, 204));
        razaoBF.setText("  BAROS FILHOS CONTABILIDADE & SERVIÇOS LTDA");
        razaoBF.setFocusable(false);
        razaoBF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        razaoBF.setPlaceholder("Razão Social");
        razaoBF.setPreferredSize(new java.awt.Dimension(200, 25));
        razaoBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                razaoBFActionPerformed(evt);
            }
        });
        panelDados.add(razaoBF, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 340, -1));

        lblRazao.setBackground(new java.awt.Color(0, 51, 204));
        lblRazao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRazao.setForeground(new java.awt.Color(255, 255, 255));
        lblRazao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRazao.setText("Razão Social");
        lblRazao.setOpaque(true);
        panelDados.add(lblRazao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 25));

        lblCNPJ.setBackground(new java.awt.Color(0, 51, 204));
        lblCNPJ.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCNPJ.setForeground(new java.awt.Color(255, 255, 255));
        lblCNPJ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCNPJ.setText("CNPJ");
        lblCNPJ.setOpaque(true);
        panelDados.add(lblCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 30, 25));

        lblEndeBF.setBackground(new java.awt.Color(0, 51, 204));
        lblEndeBF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEndeBF.setForeground(new java.awt.Color(255, 255, 255));
        lblEndeBF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEndeBF.setText("Endereço");
        lblEndeBF.setOpaque(true);
        panelDados.add(lblEndeBF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, 25));

        lblEndeBF2.setBackground(new java.awt.Color(0, 51, 204));
        lblEndeBF2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEndeBF2.setForeground(new java.awt.Color(255, 255, 255));
        lblEndeBF2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEndeBF2.setText("Tel");
        lblEndeBF2.setOpaque(true);
        panelDados.add(lblEndeBF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 30, 25));

        txtTelBF.setEditable(false);
        txtTelBF.setBackground(new java.awt.Color(255, 255, 255));
        txtTelBF.setBorder(null);
        txtTelBF.setForeground(new java.awt.Color(0, 0, 204));
        try {
            txtTelBF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelBF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelBF.setText("7921075924");
        txtTelBF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtTelBF.setPreferredSize(new java.awt.Dimension(109, 25));
        panelDados.add(txtTelBF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 120, -1));

        txtCNPJBF.setEditable(false);
        txtCNPJBF.setBackground(new java.awt.Color(255, 255, 255));
        txtCNPJBF.setBorder(null);
        txtCNPJBF.setForeground(new java.awt.Color(0, 0, 204));
        try {
            txtCNPJBF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCNPJBF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCNPJBF.setText("04.227.147/0001-70");
        txtCNPJBF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCNPJBF.setPreferredSize(new java.awt.Dimension(109, 25));
        panelDados.add(txtCNPJBF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 120, -1));

        panelCentraldoScroll.add(panelDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 660, 100));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);

        table.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        table.setForeground(new java.awt.Color(0, 51, 204));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Qtde.", "Und.", "Descrição", "Valor Un.", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.setCellSelectionEnabled(true);
        table.setDoubleBuffered(true);
        table.setDragEnabled(true);
        table.setGridColor(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        table.setIntercellSpacing(new java.awt.Dimension(4, 4));
        table.setRowHeight(25);
        table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        table.setSelectionForeground(new java.awt.Color(204, 204, 204));
        table.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setPreferredWidth(40);
            table.getColumnModel().getColumn(1).setPreferredWidth(40);
            table.getColumnModel().getColumn(2).setMinWidth(400);
            table.getColumnModel().getColumn(2).setPreferredWidth(400);
            table.getColumnModel().getColumn(2).setMaxWidth(400);
            table.getColumnModel().getColumn(3).setPreferredWidth(50);
            table.getColumnModel().getColumn(4).setPreferredWidth(60);
        }

        panelCentraldoScroll.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 307, 660, 390));

        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconLogin/add_file_32px.png"))); // NOI18N
        btnadd.setContentAreaFilled(false);
        btnadd.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconLogin/add_file_edit32px.png"))); // NOI18N
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        panelCentraldoScroll.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 30, 40));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconLogin/save_32bluepx.png"))); // NOI18N
        btnSalvar.setContentAreaFilled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        panelCentraldoScroll.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 30, -1));

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconLogin/print_32px.png"))); // NOI18N
        btnImprimir.setContentAreaFilled(false);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        panelCentraldoScroll.add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 30, -1));

        txtUnd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelCentraldoScroll.add(txtUnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 30, 25));

        txtQtde.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelCentraldoScroll.add(txtQtde, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 30, 25));
        panelCentraldoScroll.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 450, 25));

        valorUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorUNActionPerformed(evt);
            }
        });
        panelCentraldoScroll.add(valorUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 50, 25));
        panelCentraldoScroll.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 50, 25));

        panelDosDados.setViewportView(panelCentraldoScroll);

        central.add(panelDosDados, java.awt.BorderLayout.CENTER);

        getContentPane().add(central, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEndeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndeActionPerformed

    private void txtRazaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazaoActionPerformed

    }//GEN-LAST:event_txtRazaoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVendedorActionPerformed

    private void txtEndeBFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndeBFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndeBFActionPerformed

    private void razaoBFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_razaoBFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_razaoBFActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       Date data = new Date();		
	SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
     	txtData.setText(formato.format(data));
        SimpleDateFormat formatar = new SimpleDateFormat("HH:mm:ss");
       txtHora.setText(formatar.format(data));
        
        //horário automatico
       
      
    }//GEN-LAST:event_formWindowOpened

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
       
  
    
    
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void valorUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorUNActionPerformed
      
    
    }//GEN-LAST:event_valorUNActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        String qtd = txtQtde.getText().trim();
        String un = valorUN.getText().trim();
       

        DefaultTableModel val = (DefaultTableModel) table.getModel();
        val.addRow() String[] {txtQtde});
    }//GEN-LAST:event_btnaddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnadd;
    private javax.swing.JComboBox<String> cBox;
    private javax.swing.JPanel central;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblCNPJ;
    private javax.swing.JLabel lblEndeBF;
    private javax.swing.JLabel lblEndeBF2;
    private javax.swing.JLabel lblRazao;
    private javax.swing.JPanel panelCentraldoScroll;
    private javax.swing.JPanel panelDados;
    private javax.swing.JScrollPane panelDosDados;
    private app.bolivia.swing.JCTextField razaoBF;
    private javax.swing.JTable table;
    private javax.swing.JPanel top;
    private javax.swing.JFormattedTextField txtCNPJ;
    private javax.swing.JFormattedTextField txtCNPJBF;
    private app.bolivia.swing.JCTextField txtCod;
    private javax.swing.JLabel txtData;
    private app.bolivia.swing.JCTextField txtEmail;
    private app.bolivia.swing.JCTextField txtEnde;
    private app.bolivia.swing.JCTextField txtEndeBF;
    private javax.swing.JLabel txtHora;
    private app.bolivia.swing.JCTextField txtNum;
    private javax.swing.JTextField txtQtde;
    private app.bolivia.swing.JCTextField txtRazao;
    private javax.swing.JFormattedTextField txtTel;
    private javax.swing.JFormattedTextField txtTelBF;
    private javax.swing.JTextField txtUnd;
    private app.bolivia.swing.JCTextField txtVendedor;
    private javax.swing.JTextField valorUN;
    // End of variables declaration//GEN-END:variables

   
      
}      
        
        
        
        
    


